/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChangiaRouteImport } from './routes/_authenticated/changia'
import { Route as AuthenticatedJiungeRouteImport } from './routes/_authenticated/jiunge'
import { Route as AuthenticatedMikopoRouteImport } from './routes/_authenticated/mikopo'
import { Route as AuthenticatedMikutanoRouteImport } from './routes/_authenticated/mikutano'
import { Route as AuthenticatedNyumbaniRouteImport } from './routes/_authenticated/nyumbani'
import { Route as AuthenticatedPesaRouteImport } from './routes/_authenticated/pesa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangiaRoute = AuthenticatedChangiaRouteImport.update({
  id: '/changia',
  path: '/changia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJiungeRoute = AuthenticatedJiungeRouteImport.update({
  id: '/jiunge',
  path: '/jiunge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMikopoRoute = AuthenticatedMikopoRouteImport.update({
  id: '/mikopo',
  path: '/mikopo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMikutanoRoute = AuthenticatedMikutanoRouteImport.update({
  id: '/mikutano',
  path: '/mikutano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNyumbaniRoute = AuthenticatedNyumbaniRouteImport.update({
  id: '/nyumbani',
  path: '/nyumbani',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesaRoute = AuthenticatedPesaRouteImport.update({
  id: '/pesa',
  path: '/pesa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/changia': typeof AuthenticatedChangiaRoute
  '/jiunge': typeof AuthenticatedJiungeRoute
  '/mikopo': typeof AuthenticatedMikopoRoute
  '/mikutano': typeof AuthenticatedMikutanoRoute
  '/nyumbani': typeof AuthenticatedNyumbaniRoute
  '/pesa': typeof AuthenticatedPesaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/changia': typeof AuthenticatedChangiaRoute
  '/jiunge': typeof AuthenticatedJiungeRoute
  '/mikopo': typeof AuthenticatedMikopoRoute
  '/mikutano': typeof AuthenticatedMikutanoRoute
  '/nyumbani': typeof AuthenticatedNyumbaniRoute
  '/pesa': typeof AuthenticatedPesaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/changia': typeof AuthenticatedChangiaRoute
  '/_authenticated/jiunge': typeof AuthenticatedJiungeRoute
  '/_authenticated/mikopo': typeof AuthenticatedMikopoRoute
  '/_authenticated/mikutano': typeof AuthenticatedMikutanoRoute
  '/_authenticated/nyumbani': typeof AuthenticatedNyumbaniRoute
  '/_authenticated/pesa': typeof AuthenticatedPesaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/changia'
    | '/jiunge'
    | '/mikopo'
    | '/mikutano'
    | '/nyumbani'
    | '/pesa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/changia'
    | '/jiunge'
    | '/mikopo'
    | '/mikutano'
    | '/nyumbani'
    | '/pesa'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/changia'
    | '/_authenticated/jiunge'
    | '/_authenticated/mikopo'
    | '/_authenticated/mikutano'
    | '/_authenticated/nyumbani'
    | '/_authenticated/pesa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/changia': {
      id: '/_authenticated/changia'
      path: '/changia'
      fullPath: '/changia'
      preLoaderRoute: typeof AuthenticatedChangiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jiunge': {
      id: '/_authenticated/jiunge'
      path: '/jiunge'
      fullPath: '/jiunge'
      preLoaderRoute: typeof AuthenticatedJiungeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mikopo': {
      id: '/_authenticated/mikopo'
      path: '/mikopo'
      fullPath: '/mikopo'
      preLoaderRoute: typeof AuthenticatedMikopoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mikutano': {
      id: '/_authenticated/mikutano'
      path: '/mikutano'
      fullPath: '/mikutano'
      preLoaderRoute: typeof AuthenticatedMikutanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nyumbani': {
      id: '/_authenticated/nyumbani'
      path: '/nyumbani'
      fullPath: '/nyumbani'
      preLoaderRoute: typeof AuthenticatedNyumbaniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesa': {
      id: '/_authenticated/pesa'
      path: '/pesa'
      fullPath: '/pesa'
      preLoaderRoute: typeof AuthenticatedPesaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChangiaRoute: typeof AuthenticatedChangiaRoute
  AuthenticatedJiungeRoute: typeof AuthenticatedJiungeRoute
  AuthenticatedMikopoRoute: typeof AuthenticatedMikopoRoute
  AuthenticatedMikutanoRoute: typeof AuthenticatedMikutanoRoute
  AuthenticatedNyumbaniRoute: typeof AuthenticatedNyumbaniRoute
  AuthenticatedPesaRoute: typeof AuthenticatedPesaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChangiaRoute: AuthenticatedChangiaRoute,
  AuthenticatedJiungeRoute: AuthenticatedJiungeRoute,
  AuthenticatedMikopoRoute: AuthenticatedMikopoRoute,
  AuthenticatedMikutanoRoute: AuthenticatedMikutanoRoute,
  AuthenticatedNyumbaniRoute: AuthenticatedNyumbaniRoute,
  AuthenticatedPesaRoute: AuthenticatedPesaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
